"""empty message

Revision ID: 54769d2845ab
Revises: fd1b3fd7e473
Create Date: 2025-08-07 16:54:34.587257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54769d2845ab'
down_revision = 'fd1b3fd7e473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
